name: Update RO Status

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch: # Позволяет запустить вручную кнопкой

# Добавляем этот блок здесь
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # В 2026 году рекомендуется использовать v6
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' # Рекомендуется актуальная версия

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run parser
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add status.json
          # Если файл не изменился, commit вернет ошибку, поэтому используем || exit 0
          git commit -m "Update status [skip ci]" || exit 0
          git push
